name: CI

on:
  push:
    paths:
      - "**.v"
    branches: [main]

jobs:

  windows-build:
    runs-on: windows-2019
    env:
        VFLAGS: -cc msvc
        VJOBS: 1
        VTEST_SHOW_START: 1
        DATE: date /t
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Symlink
        run: |
          C:\hostedtoolcache\windows\v\0.3.0\x64\v.exe symlink

      - name: Copy SQLite files for Windows compile
        working-directory: thirdparty
        run: |
            mkdir -p C:\hostedtoolcache\windows\v\0.3.0\x64\thirdparty\sqlite
            cp * C:\hostedtoolcache\windows\v\0.3.0\x64\thirdparty\sqlite

      - name: Download SQLite GUI
        run: |
            curl -L -O https://github.com/little-brother/sqlite-gui/releases/download/1.7.5/sqlite-gui.1.7.5-x64.zip
            7z x sqlite-gui.1.7.5-x64.zip

      - name: Build
        run: |
          v -prod -cc msvc src/xerdiff.v -o xerdiff.exe
          v -prod -cc msvc src/xertask.v -o xertask.exe
          v -prod -cc msvc src/xerdump.v -o xerdump.exe
          v -prod -cc msvc src/xerpred.v -o xerpred.exe
          v -prod -cc msvc src/xer2json.v -o xer2json.exe
          v -prod -cc msvc src/sqlrunner.v -o sqlrunner.exe

      - name: Make zip
        run: |
          powershell Compress-Archive xertask.exe,xerdiff.exe,xerdump.exe,xerpred.exe,xer2json.exe,sqlrunner.exe,examples,README.md,LICENSE,sqlite3.dll,sqlite-gui.exe,extensions xertools_latest_win64.zip

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: beta
          files: |
            xertask.exe
            xerdump.exe
            xerdiff.exe
            xerpred.exe
            xer2json.exe
            sqlrunner.exe
            xertools_latest_win64.zip

  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Check if code is formatted
        run:  |
          v fmt -diff .
          v fmt -verify .
      
      - name: Build ${{ github.event.repository.name }} - xerdump
        run:
          v src/xerdump.v

      - name: Build ${{ github.event.repository.name }} - xerdiff
        run:
          v src/xerdiff.v

      - name: Build ${{ github.event.repository.name }} - xertask
        run:
          v src/xertask.v

      - name: Build ${{ github.event.repository.name }} - xerpred
        run:
          v src/xerpred.v

      - name: Build ${{ github.event.repository.name }} - xer2json
        run:
          v src/xer2json.v

      - name: Build ${{ github.event.repository.name }} - sqlrunner
        run:
          v src/sqlrunner.v
         
      - name: Run Tests
        run: v test .
        env:
          VJOBS: 1

      #- name: Install MinGW for cross-compile
      #  run: sudo apt-get install gcc-mingw-w64-x86-64

      #- name: Copy SQLite files for Windows cross-compile
      #  working-directory: thirdparty
      #  run: |
      #      mkdir -p /opt/hostedtoolcache/v/0.3.0/x64/thirdparty/sqlite/
      #      cp * /opt/hostedtoolcache/v/0.3.0/x64/thirdparty/sqlite/

      - name: Make production binaries
        working-directory: src
        run: |
            ./build.sh

      - name: Make zips
        run: |
            zip -r xertools_latest_linux.zip xerdiff xerdump xertask xerpred xer2json examples/ LICENSE README.md

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: beta
          files: |
            xertask
            xerdump
            xerdiff
            xerpred
            xer2json
            sqlrunner
            xertools_latest_linux.zip